"""create escalations table

Revision ID: 097010ca093c
Revises: 67ec07ff7e11
Create Date: 2026-10-07 23:29:44.455619

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097010ca093c'
down_revision: Union[str, Sequence[str], None] = '67ec07ff7e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('output_id', sa.UUID(), nullable=False),
    postgresql.ENUM(
    'none',
    'low',
    'medium',
    'high',
    name='risk_tier',
    create_type=False
),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'FALSE_POSITIVE', name='case_status'), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('counselor_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['output_id'], ['agent_outputs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escalations')
    # ### end Alembic commands ###
