"""create prompt versions table

Revision ID: 5e27c96e532c
Revises: 13cc18069f7e
Create Date: 2026-10-07 23:51:48.421242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e27c96e532c'
down_revision: Union[str, Sequence[str], None] = '13cc18069f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.Enum('CONVERSATION', 'MOOD_ANALYSIS', 'MEMORY_PATTERN', 'THERAPEUTIC', 'CRISIS_DETECTION', name='agentkind'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
