"""create agent outputs table

Revision ID: 67ec07ff7e11
Revises: 353bea1a18a2
Create Date: 2026-10-07 23:23:24.751921

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ec07ff7e11'
down_revision: Union[str, Sequence[str], None] = '353bea1a18a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.Enum('CONVERSATION', 'MOOD_ANALYSIS', 'MEMORY_PATTERN', 'THERAPEUTIC', 'CRISIS_DETECTION', name='agent_kind'), nullable=False),
    sa.Column('wellness_score', sa.SmallInteger(), nullable=True),
    sa.Column('sentiment', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('primary_emotion', sa.String(), nullable=True),
    sa.Column('depression_type', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('minimal', 'mild', 'moderate', 'moderately_severe', 'severe', name='severity_band'), nullable=True),
    sa.Column(
    'risk_tier',
    postgresql.ENUM(
        'none',
        'low',
        'medium',
        'high',
        name='risk_tier',
        create_type=False
    ),
    nullable=True
),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'agent', name='uq_agent_outputs_message_agent')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_outputs')
    # ### end Alembic commands ###
