"""create consents table

Revision ID: a6d5214bb7e9
Revises: ff12bb148f65
Create Date: 2026-10-07 23:41:15.727183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d5214bb7e9'
down_revision: Union[str, Sequence[str], None] = 'ff12bb148f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('data_consent', sa.Boolean(), nullable=False),
    sa.Column('ai_consent', sa.Boolean(), nullable=False),
    sa.Column('counselor_consent', sa.Boolean(), nullable=False),
    sa.Column('emergency_contact_consent', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consents')
    # ### end Alembic commands ###
