"""create student memories table

Revision ID: ff12bb148f65
Revises: 097010ca093c
Create Date: 2026-10-07 23:35:29.134057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff12bb148f65'
down_revision: Union[str, Sequence[str], None] = '097010ca093c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('wellness_trend', sa.Enum('IMPROVING', 'STABLE', 'DECLINING', 'UNKNOWN', name='wellnesstrend'), nullable=False),
    sa.Column('baseline_wellness', sa.Integer(), nullable=True),
    sa.Column('current_wellness', sa.Integer(), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('effective_interventions', sa.JSON(), nullable=True),
    sa.Column('ineffective_interventions', sa.JSON(), nullable=True),
    sa.Column('phq9_score', sa.Integer(), nullable=True),
    sa.Column('phq9_severity', sa.String(length=50), nullable=True),
    sa.Column('context_card', sa.JSON(), nullable=True),
    sa.Column('pattern_findings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.add_column('escalations', sa.Column('tier', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='risk_tier'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escalations', 'tier')
    op.drop_table('student_memories')
    # ### end Alembic commands ###
